#!/bin/bash

R CMD javareconf -e

Rscript binder/install_.R

# Prevent timeout while downloading the dataset
Rscript -e 'europarl::europarl_download()'

# https://github.com/PolMine/GermaParl/issues/21
Rscript binder/install_GermaParl.R